files:
  - source: admin-client/android/app/src/main/res/values/strings.xml
    translation: >-
      admin-client/android/app/src/main/res/values-%two_letters_code%/strings.xml
  - source: android-client/app/src/main/res/values/strings.xml
    translation: android-client/app/src/main/res/values-%two_letters_code%/strings.xml
