//Geolocation Constants
export const UPDATE_LANGUAGE = 'update_language';
export const UPDATE_DIRECTION = 'update_direction';

//Project Constants
export const ALL_PROJECTS_SUCCESS = 'ALL_PROJECTS_SUCCESS';
export const ALL_PROJECTS_FAILED = 'ALL_PROJECTS_FAILED';
export const ALL_PROJECTS_LOADING = 'ALL_PROJECTS_LOADING';
export const PROJECT_DELETED = 'PROJECT_DELETED';

//User Constants
export const FETCHING_USERS = 'FETCHING_USERS';
export const LOADING_USER = 'LOADING_USER';
export const FETCHED_USERS = 'FETCHED_USERS';
export const PATCHED_USER = 'PATCHED_USER';
export const DELETED_USER = 'DELETED_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_LOGGED_USER_HASH = 'GET_LOGGED_USER_HASH';
export const REMOVE_USER = 'REMOVE_USER';
export const USER_FAILED = 'USER_FAILED';

//Settings Constants
export const LOCALIZATION_SUCCESS = 'LOCALIZATION_SUCCESS';
export const LOCALIZATION_FAILED = 'LOCALIZATION_FAILED';
export const LOCALIZATION_FETCHING = 'LOCALIZATION_FETCHING';
export const IMPORT_LOCALIZATION = 'IMPORT_LOCALIZATION';
export const LOCALIZATION_DOWNLOADED = 'LOCALIZATION_DOWNLOADED';